name: my-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build1:

    runs-on: ubuntu-latest

    steps:
    - name: Print first Hello 
      run: echo "Hi github Actions ONE!"
   
  build2:

    runs-on: ubuntu-latest 
    
    steps:
    - name: Print  second Hello 
      run: echo "Hi github Actions TWO!"
